### PR TITLE
Bump intl version for new flutter 3.22

### PR DESCRIPTION
**Pull request by Mowinski**

### CODE REVIEW

**Comment by Zsmerritt** [comment]
Looks good. Thanks for the increment. Will publish later today if the build is successful

**Comment by Mowinski** [comment]
Sure ;) but I see the CI fails from some reason. I will try to fix it but it looks like not releated to my changes :)

**Comment by Zsmerritt** [comment]
Can you remove the following lint lines from analysis options? The were removed in 3.3.0

iterable_contains_unrelated_type
list_remove_unrelated_type

**Comment by Mowinski** [comment]
Good point :) thanks

**Comment by Zsmerritt** [comment]
Merged! Thanks so much. I’ll publish a new version in a bit

**Pull request merged**
